apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
  annotations:
    greymatter.io/configure-sidecar: "false"
spec:
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      labels:
        app: apple
    spec:
      containers:
        - name: apple
          image: python:3
          command: ["python"]
          args: ["-m", "http.server", "42071"]
          ports:
          - name: ingress
            containerPort: 42071
